### ISSUE TITLE
When there are multiple cells open, the animation will beat when the cell at the end is closed.

### ISSUE THREAD

**Issue by HelloWk** [Ramotion/folding-cell#162] opened 2018-10-10 04:04 UTC
hi,

When there are multiple cells open, the animation will beat when the cell at the end is closed.

I guess it may be a height calculation error.

**Comment by c941010623** [comment] 2018-10-14 14:55
i have some problem

**Comment by c941010623** [comment] 2018-10-23 13:11
fist open demo
then open cell 8
then open cell 9 
bug will show you

**Comment by rbarbish** [comment] 2018-11-02 16:45
Anyone find a fix yet? Probably going to dig into it soon if no one has anything

**Comment by 368433** [comment] 2018-11-08 00:20
same here, I tried to adjust parameters (cell heights, animation speed, etc...) but cannot find why it does that.
Everything is fine as long as no table scrolling has happened. Once you scroll down and expand a cell, the odd behaviour happens. I can attach a gif if it can help describe the problem

**Comment by 0ber** [comment] 2019-04-23 09:47
Duplicate of #169

**Closed by 0ber** 2019-04-23 09:47 UTC
